-- Crear Tablespace CB (CorBesso)
-- CB: DATA
CREATE TABLESPACE CB_Data
DATAFILE 'C:\app\sam\oradata\lab00sammy\CBdata01.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;
--
-- CB: INDEX
CREATE TABLESPACE CB_Ind
DATAFILE 'C:\app\sam\oradata\lab00sammy\CBind01.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;
