-- CATALOGO: TIPO DE USUARIO
CREATE TABLE TIPO_USUARIO
(
       TIPO_USUARIO_ID  NUMBER(6),
       CONSTRAINT       PK_TIPO_USUARIO PRIMARY KEY(TIPO_USUARIO_ID),
       
       ADMINISTRADOR    CHAR(1)         CONSTRAINT TIPO_USUARIO_NOMBRE_NN NOT NULL,--BOOL
       
       EMAIL            VARCHAR2(30)   CONSTRAINT TIPO_USUARIO_EMAIL_NN NOT NULL,
       CONSTRAINT TIPO_USUARIO_EMAIL_UK UNIQUE (EMAIL),
       
       CONTRASENA       VARCHAR2(8)    CONSTRAINT TIPO_USUARIO_CONTRASENA_NN NOT NULL,
       
       -- Atributos de Auditoria
       Fec_creacion 	  DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT ON TABLE TIPO_USUARIO IS 'CATALOGO EL TIPO DE USUARIO';
