CREATE TABLE ACTIVIDAD_RECREATIVA
(
  ACTIVIDAD_RECREATIVA_ID NUMBER(6),
  CONSTRAINT PK_ACTIVIDAD_RECREATIVA PRIMARY KEY(ACTIVIDAD_RECREATIVA_ID),
  NOMBRE VARCHAR2(15) CONSTRAINT ACTIVIDAD_RECREATIVA_NOMBRE_NN NOT NULL
);
