-- CATALOGO: DE RELIGION
CREATE TABLE RELIGION
(
	RELIGION_ID NUMBER(6),
	CONSTRAINT PK_RELIGION PRIMARY KEY(RELIGION_ID),
	NOMBRE VARCHAR2(15) CONSTRAINT RELIGION_NOMBRE_NN NOT NULL,
  
	-- Atributos de Auditoria
    Fec_creacion 	  DATE,
    Usuario_creacion   VARCHAR2(10),
    Fec_ultima_modificacion     DATE,
    Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT ON TABLE RELIGION IS 'CATALOGO PARA RELIGION';
