-- CATALOGO: CONTEXTURA
CREATE TABLE CONTEXTURA
(
  CONTEXTURA_ID NUMBER(6),
  CONSTRAINT PK_CONTEXTURA PRIMARY KEY(CONTEXTURA_ID),
  TIPO VARCHAR2(50) CONSTRAINT CONTEXTURA_TIPO_NN NOT NULL,
  -- Atributos de Auditoria
       Fec_creacion 	  DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT ON TABLE CONTEXTURA IS 'CATALOGO PARA CONTEXTURA';
