-- CATALOGO: OCUPACION
CREATE TABLE OCUPACION
(
  OCUPACION_ID NUMBER(6),
  CONSTRAINT PK_OCUPACION PRIMARY KEY(OCUPACION_ID),
  NIVEL VARCHAR2(50) CONSTRAINT OCUPACION_NIVEL_NN NOT NULL,
  -- Atributos de Auditoria
       Fec_creacion 	  DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT TABLE OCUPACION IS 'CATALOGO DE OCUPACION';
