--TABLA SIGNO ZODIACAL
CREATE TABLE SIGNO_ZODIACAL
(
  SIGNO_ZODIACAL_ID NUMBER(6),
  CONSTRAINT PK_SIGNO_ZODIACAL PRIMARY KEY(SIGNO_ZODIACAL_ID),
  NOMBRE VARCHAR2(20) CONSTRAINT SIGNO_ZODIACAL_NOMBRE_NN NOT NULL
);

--ID NOMBRE
