-- CATALOGO: ESCOLARIDAD
CREATE TABLE ESCOLARIDAD
(
  ESCOLARIDAD_ID NUMBER(6),
  CONSTRAINT PK_ESCOLARIDAD PRIMARY KEY(ESCOLARIDAD_ID),
  NIVEL VARCHAR2(50) CONSTRAINT ESCOLARIDAD_NIVEL_NN NOT NULL,
  -- Atributos de Auditoria
       Fec_creacion 	  DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT TABLE ESCOLARIDAD IS 'CATALOGO DE ESCOLARIDAD';
