--COMMENTS DE CAMPOS DE TABLAS

--ACTIVIDAD_RECREATIVA
COMMENT ON COLUMN ACTIVIDAD_RECREATIVA.ACTIVIDAD_RECREATIVA_ID
IS 'Identificador de la Actividad Recreativa';    
COMMENT ON COLUMN ACTIVIDAD_RECREATIVA.NOMBRE
IS 'Nombre de la Actividad Recreativa';    
COMMENT ON COLUMN ACTIVIDAD_RECREATIVA.FEC_CREACION
IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ACTIVIDAD_RECREATIVA.USUARIO_CREACION
IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ACTIVIDAD_RECREATIVA.FEC_ULTIMA_MODIFICACION
IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ACTIVIDAD_RECREATIVA.USUARIO_ULTIMA_MODIFICACION
IS 'CAMPO AUDITORIA';


--CAMPOS AUDITORIA
COMMENT ON COLUMN .FEC_CREACION
IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN .USUARIO_CREACION
IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN .FEC_ULTIMA_MODIFICACION
IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN .USUARIO_ULTIMA_MODIFICACION
IS 'CAMPO AUDITORIA';
