CREATE TABLE PERSONA
(
       PERSONA_ID       NUMBER(6),
       CONSTRAINT       PK_PERSONA PRIMARY KEY(PERSONA_ID),
       NOMBRE           VARCHAR2(20)    CONSTRAINT PERSONA_NOMBRE_NN NOT NULL,
       PRIMER_APELLIDO  VARCHAR2(20)    CONSTRAINT PERSONA_PRIMER_APELLIDO_NN NOT NULL,
       SEGUNDO_APELLIDO VARCHAR2(20)    CONSTRAINT PERSONA_SEGUNDO_APELLIDO_NN NOT NULL,
       NACIMIENTO       DATE            CONSTRAINT PERSONA_NACIMIENTO_NN NOT NULL,
       FOTO             VARCHAR2(20)    CONSTRAINT PERSONA_FOTO_NN NOT NULL,
       SLOGAN           VARCHAR2(150)   CONSTRAINT PERSONA_SLOGAN_NN NOT NULL,
       CANT_HIJOS       NUMBER(2)       CONSTRAINT PERSONA_CANT_HIJOS_NN NOT NULL,
       QUIERE_HIJOS     NUMBER(1)       CONSTRAINT PERSONA_QUIERE_HIJOS_NN NOT NULL,
       CONSTRAINT PERSONA_HIJOS_MAX CHECK (QUIERE_HIJOS<=1)
);
