CREATE TABLE TIPO_USUARIO
(
       TIPO_USUARIO_ID  NUMBER(6),
       CONSTRAINT       PK_TIPO_USUARIO PRIMARY KEY(TIPO_USUARIO_ID),
       NOMBRE           VARCHAR2(4)    CONSTRAINT TIPO_USUARIO_NOMBRE_NN NOT NULL,--ADMI,USER
       EMAIL            VARCHAR2(30)   CONSTRAINT TIPO_USUARIO_EMAIL_NN NOT NULL,
       CONSTRAINT TIPO_USUARIO_EMAIL_UK UNIQUE (EMAIL),
       CONTRASENA       VARCHAR2(8)    CONSTRAINT TIPO_USUARIO_CONTRASENA_NN NOT NULL
);
