--TABLA EMAIL_x_PERSONA
CREATE TABLE EMAIL_x_PERSONA
(
  EMAIL_x_PERSONA_ID NUMBER(6),
  CONSTRAINT PK_EMAIL_x_PERSONA PRIMARY KEY(EMAIL_x_PERSONA_ID),
  
  PERSONA_ID NUMBER(6),
  CONSTRAINT FK_PERSONA FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID),
  
  EMAIL_ID NUMBER(6),
  CONSTRAINT FK_EMAIL FOREIGN KEY (EMAIL_ID) REFERENCES EMAIL(EMAIL_ID)

);

