--TABLA: EVENTO
CREATE TABLE EVENTO
(
       EVENTO_ID NUMBER(6),
       CONSTRAINT PK_EVENTO_ID PRIMARY KEY (EVENTO_ID),
       
       FECHA_EVENTO DATE CONSTRAINT EVENTO_FECHA_EVENTO_NN NOT NULL,
       
       --HORA_EVENTO  DATE(HH24) CONSTRAINT EVENTO_HORA_EVENTO_NN NOT NULL,
       
       PAIS_ID NUMBER(6),
       CONSTRAINT FK_PAIS_ID FOREIGN KEY (PAIS_ID) REFERENCES PAIS(PAIS_ID),
       
       CIUDAD_ID NUMBER(6),
       CONSTRAINT FK_CIUDAD_ID FOREIGN KEY (CIUDAD_ID) REFERENCES CIUDAD(CIUDAD_ID),
       
       FRECUENCIA_ID NUMBER(6),
       CONSTRAINT FK_FRECUENCIA_HxP FOREIGN KEY (FRECUENCIA_ID) REFERENCES FRECUENCIA(FRECUENCIA_ID),
       
       -- Atributos de Auditoria
       Fec_creacion 	  DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT ON TABLE HOBBIE_x_PERSONA IS 'TABLA DE LOS HOBBIE DE UNA PERSONA';
