--TABLA LUGAR_EVENTO
CREATE TABLE LUGAR_EVENTO
(
  LUGAR_EVENTO_ID NUMBER(6),
  CONSTRAINT PK_LUGAR_EVENTO PRIMARY KEY(LUGAR_EVENTO_ID),
  
  PUNTO_REUNION VARCHAR2(20) CONSTRAINT LUGAR_EVENTO_PUNTO_REUNION_NN NOT NULL,
  
  CIUDAD_ID NUMBER(6),
  CONSTRAINT FK_CIUDAD FOREIGN KEY (CIUDAD_ID) REFERENCES CIUDAD(CIUDAD_ID)
);

--ID PUNTO_REUNION CIUDAD_ID
