CREATE TABLE MASCOTA
(
       MASCOTA_ID       NUMBER(6),
       CONSTRAINT       PK_MASCOTA            PRIMARY KEY(MASCOTA_ID),
       AFINIDAD         NUMBER(1)             CONSTRAINT MASCOTA_AFINIDAD_NN NOT NULL,
       CONSTRAINT       MASCOTA_AFINIDAD_BOOL CHECK (AFINIDAD<=1),
       DISPONIBILIDAD   NUMBER(1)             CONSTRAINT MASCOTA_DISPONIBILIDAD_NN NOT NULL,
       CONSTRAINT       MASCOTA_DISPONIBILIDAD_BOOL CHECK (DISPONIBILIDAD<=1)
);
