CREATE TABLE HOBBIE_x_PERSONA
(
  HOBBIE_x_PERSONA_ID NUMBER(6),
  CONSTRAINT PK_HOBBIE_x_PERSONA PRIMARY KEY(HOBBIE_x_PERSONA_ID),
  
  PERSONA_ID NUMBER(6),
  CONSTRAINT FK_PERSONAH FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID),
  
  HOBBIE_ID NUMBER(6),
  CONSTRAINT FK_HOBBIEH FOREIGN KEY (HOBBIE_ID) REFERENCES HOBBIE(HOBBIE_ID)
);
