CREATE TABLE Vicio_x_Persona
(
       VICIO_x_PERSONA_ID NUMBER(6),
       CONSTRAINT PK_VICIO_x_PERSONA PRIMARY KEY (VICIO_x_PERSONA_ID),
       
       VICIO_ID NUMBER(6),
       CONSTRAINT FK_VICIO FOREIGN KEY(VICIO_ID) REFERENCES VICIO(VICIO_ID),
       
       PERSONA_ID NUMBER(6),
       CONSTRAINT FK_PERSONA_VxP FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID),
       
       FRECUENCIA_ID NUMBER(6),
       CONSTRAINT FK_FRECUENCIA_VxP FOREIGN KEY (FRECUENCIA_ID) REFERENCES FRECUENCIA(FRECUENCIA_ID)
);
