--ACTIVIDAD_RECREATIVA

--ACTIVIDAD_X_PERSONA 

COMMENT ON COLUMN ACTIVIDAD_X_PERSONA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ACTIVIDAD_X_PERSONA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ACTIVIDAD_X_PERSONA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ACTIVIDAD_X_PERSONA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--ALTURA
COMMENT ON COLUMN ALTURA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ALTURA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ALTURA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ALTURA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--BUSCAR 
--CCABELLO
COMMENT ON COLUMN CCABELLO.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CCABELLO.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CCABELLO.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CCABELLO.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--CIUDAD
COMMENT ON COLUMN CIUDAD.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CIUDAD.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CIUDAD.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CIUDAD.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--COJOS 
COMMENT ON COLUMN COJOS.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN COJOS.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN COJOS.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN COJOS.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--CONTEXTURA
COMMENT ON COLUMN CONTEXTURA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CONTEXTURA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CONTEXTURA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CONTEXTURA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--CPIEL
COMMENT ON COLUMN CPIEL.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CPIEL.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CPIEL.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN CPIEL.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--DEPORTE
COMMENT ON COLUMN DEPORTE.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN DEPORTE.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN DEPORTE.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN DEPORTE.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--DEPORTE_X_PERSONA
COMMENT ON COLUMN DEPORTE_X_PERSONA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN DEPORTE_X_PERSONA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN DEPORTE_X_PERSONA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN DEPORTE_X_PERSONA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--EDAD
COMMENT ON COLUMN EDAD.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EDAD.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EDAD.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EDAD.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--EMAIL_X_PERSONA
COMMENT ON COLUMN EMAIL_X_PERSONA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EMAIL_X_PERSONA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EMAIL_X_PERSONA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EMAIL_X_PERSONA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--ESCOLARIDAD
COMMENT ON COLUMN ESCOLARIDAD.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ESCOLARIDAD.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ESCOLARIDAD.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN ESCOLARIDAD.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

---EST_CIVIL
COMMENT ON COLUMN EST_CIVIL.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EST_CIVIL.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EST_CIVIL.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EST_CIVIL.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--EVENTO
COMMENT ON COLUMN EVENTO.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EVENTO.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EVENTO.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN EVENTO.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--FRECUENCIA
COMMENT ON COLUMN FRECUENCIA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN FRECUENCIA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN FRECUENCIA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN FRECUENCIA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--HOBBIE
COMMENT ON COLUMN HOBBIE.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN HOBBIE.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN HOBBIE.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN HOBBIE.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--HOBBIE_X_PERSONA
COMMENT ON COLUMN HOBBIE_X_PERSONA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN HOBBIE_X_PERSONA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN HOBBIE_X_PERSONA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN HOBBIE_X_PERSONA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--IDIOMA
COMMENT ON COLUMN IDIOMA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN IDIOMA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN IDIOMA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN IDIOMA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--IDIOMA_X_PERSONA
COMMENT ON COLUMN IDIOMA_X_PERSONA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN IDIOMA_X_PERSONA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN IDIOMA_X_PERSONA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN IDIOMA_X_PERSONA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--OCUPACION
COMMENT ON COLUMN OCUPACION.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN OCUPACION.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN OCUPACION.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN OCUPACION.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--PAIS
COMMENT ON COLUMN PAIS.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PAIS.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PAIS.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PAIS.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--PESO
COMMENT ON COLUMN PESO.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PESO.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PESO.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PESO.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--RELIGION
COMMENT ON COLUMN RELIGION.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN RELIGION.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN RELIGION.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN RELIGION.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--SALARIO 
COMMENT ON COLUMN SALARIO.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN SALARIO.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN SALARIO.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN SALARIO.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--SIGNO_ZODIACAL
COMMENT ON COLUMN SIGNO_ZODIACAL.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN SIGNO_ZODIACAL.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN SIGNO_ZODIACAL.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN SIGNO_ZODIACAL.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--TIPO_USUARIO
COMMENT ON COLUMN TIPO_USUARIO.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN TIPO_USUARIO.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN TIPO_USUARIO.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN TIPO_USUARIO.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--VICIO
COMMENT ON COLUMN VICIO.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN VICIO.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN VICIO.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN VICIO.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--VICIO_X_PERSONA
COMMENT ON COLUMN VICIO_X_PERSONA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN VICIO_X_PERSONA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN VICIO_X_PERSONA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN VICIO_X_PERSONA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--PARAMETROS
COMMENT ON COLUMN PARAMETROS.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PARAMETROS.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PARAMETROS.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PARAMETROS.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--PERSONA
COMMENT ON COLUMN PERSONA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PERSONA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PERSONA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN PERSONA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';

--BITACORA_VISIT
--BITACORA_MATCH
--BITACORA_WINKS
--TEL_X_PERSONA 
