--TABLA: BITACORA_WINKS

/*
Fecha: 25/09/2015
Autor: Samantha Arburola
DescripciOn: Tabla para almacenar las visitas de al perfil de una persona
*/

CREATE TABLE BITACORA_visit
(
  PERSONA_ID NUMBER(6),
  CONSTRAINT FK_PERSONA_b_visit FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID),
  
  visit_ID NUMBER(6),
  CONSTRAINT FK_visit FOREIGN KEY (visit_ID) REFERENCES PERSONA(PERSONA_ID),
  
  CONSTRAINT PK_BIT_visit PRIMARY KEY (visit_ID, PERSONA_ID),
  
  Fec_visit   DATE,
  
  
       -- Atributos de Auditoria
       Fec_creacion 	  DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT ON TABLE BITACORA_visit IS 'TABLA PARA BITACORA DE visitas POR USUARIO';

COMMENT ON TABLE BITACORA_VISIT IS 'TABLA PARA BITACORA DE VISITAS POR USUARIO';
COMMENT ON COLUMN BITACORA_VISIT.PERSONA_ID IS 'LLAVE FORANEA, IDENTIFICADOR DE PERSONA';    
COMMENT ON COLUMN BITACORA_VISIT.VISIT_ID IS 'LLAVE PRIMARIA DE BITACORA_VISIT'; 
COMMENT ON COLUMN BITACORA_VISIT.FEC_VISIT IS 'FECHA DE LA VISITA A LA PERSONA';    

COMMENT ON COLUMN BITACORA_VISIT.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN BITACORA_VISIT.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN BITACORA_VISIT.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN BITACORA_VISIT.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
