--TABLA: BITACORA_MATCH
CREATE TABLE BITACORA_MATCH
(
  PERSONA_ID NUMBER(6),
  CONSTRAINT FK_PERSONA_b_match FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID),  
  MATCH_ID NUMBER(6),
  CONSTRAINT FK_MATCH FOREIGN KEY (MATCH_ID) REFERENCES PERSONA(PERSONA_ID),  
  CONSTRAINT PK_BIT_MATCH PRIMARY KEY (MATCH_ID, PERSONA_ID),  
  Fec_MATCH   DATE,
  
       -- Atributos de Auditoria
       Fec_creacion     DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT ON TABLE BITACORA_MATCH IS 'TABLA PARA BITACORA DE MATCH POR USUARIO';

COMMENT ON COLUMN BITACORA_MATCH.PERSONA_ID IS 'LLAVE FORANEA, IDENTIFICADOR DE PERSONA';    
COMMENT ON COLUMN BITACORA_MATCH.MATCH_ID IS 'LLAVE PRIMARIA DE BITACORA_MATCH'; 
COMMENT ON COLUMN BITACORA_MATCH.FEC_MATCH IS 'FECHA DEL MATCH CON LA PERSONA';    

COMMENT ON COLUMN BITACORA_MATCH.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN BITACORA_MATCH.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN BITACORA_MATCH.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN BITACORA_MATCH.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
