--TABLA: IDIOMA_X_PERSONA
CREATE TABLE IDIOMA_X_PERSONA
(
  IDIOMA_X_PERSONA_ID NUMBER(6),
  CONSTRAINT PK_IDIOMA_X_PERSONA PRIMARY KEY(IDIOMA_X_PERSONA_ID),
  
  PERSONA_ID NUMBER(6),
  CONSTRAINT FK_PERSONA_I FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID),
  
  
  IDIOMA_ID NUMBER(6),
  CONSTRAINT FK_IDIOMA_IxP FOREIGN KEY (IDIOMA_ID) REFERENCES IDIOMA(IDIOMA_ID),
  
  
  -- Atributos de Auditoria
       Fec_creacion 	  DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)

);

COMMENT ON TABLE IDIOMA_X_PERSONA IS 'TABLA PARA VARIOSIDIOMAS DE MISMA PERSONA';
