--TABLA: EMAIL_X_PERSONA
CREATE TABLE TEL_X_PERSONA
(
  TEL_ID NUMBER(6),
  CONSTRAINT PK_TEL PRIMARY KEY(TEL_ID),
  
  TEL number(11) CONSTRAINT TEL_TEL_NN NOT NULL,
  
  PERSONA_ID NUMBER(6),
  CONSTRAINT FK_PERSONA_txp FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID),
  
  
  -- Atributos de Auditoria
       Fec_creacion     DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)

);

COMMENT ON TABLE TEL_X_PERSONA IS 'TABLA PARA VARIOS TELEFONOS DE MISMA PERSONA';

COMMENT ON COLUMN TEL_X_PERSONA.PERSONA_ID IS 'LLAVE FORANEA, IDENTIFICADOR DE PERSONA';    
COMMENT ON COLUMN TEL_X_PERSONA.TEL_ID IS 'LLAVE PRIMARIA DE TELEFONO'; 
COMMENT ON COLUMN TEL_X_PERSONA.TEL IS 'NUMERO TELEFONICO';    

COMMENT ON COLUMN TEL_X_PERSONA.FEC_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN TEL_X_PERSONA.USUARIO_CREACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN TEL_X_PERSONA.FEC_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
COMMENT ON COLUMN TEL_X_PERSONA.USUARIO_ULTIMA_MODIFICACION IS 'CAMPO AUDITORIA';
