--TABLA EVENTO
CREATE TABLE EVENTO
(
  EVENTO_ID NUMBER(6),
  CONSTRAINT PK_EVENTO PRIMARY KEY(EVENTO_ID),
  NOMBRE VARCHAR2(50) CONSTRAINT EVENTO_NOMBRE_NN NOT NULL,
  DESCRIPCION VARCHAR2(100) CONSTRAINT EVENTO_DESCRIPCION_NN NOT NULL,
  FECHA DATE CONSTRAINT EVENTO_FECHA_NN NOT NULL,
  
  LUGAR_EVENTO_ID NUMBER(6),
  CONSTRAINT FK_LUGAR_EVENTO FOREIGN KEY (LUGAR_EVENTO_ID) REFERENCES LUGAR_EVENTO(LUGAR_EVENTO_ID)
);

--ID NOMBRE DESCRIPCION FECHA FKEVENTO
