--TABLA EVENTO

/*
Fecha: 12/09/2015
Autor: MAriela Barrantes
DescripciOn: Tabla para eventos de reuniOn de usuario
*/
CREATE TABLE EVENTO
(
  EVENTO_ID NUMBER(6),
  CONSTRAINT PK_EVENTO PRIMARY KEY(EVENTO_ID),
  NOMBRE VARCHAR2(50) CONSTRAINT EVENTO_NOMBRE_NN NOT NULL,
  DESCRIPCION VARCHAR2(100) CONSTRAINT EVENTO_DESCRIPCION_NN NOT NULL,
  FECHA DATE CONSTRAINT EVENTO_FECHA_NN NOT NULL,

  PAIS_ID NUMBER(6),
  CONSTRAINT FK_PAIS_ID FOREIGN KEY (PAIS_ID) REFERENCES PAIS(PAIS_ID),
  
  CIUDAD_ID NUMBER(6),
  CONSTRAINT FK_CIUDAD_ID FOREIGN KEY (CIUDAD_ID) REFERENCES CIUDAD(CIUDAD_ID),
       -- Atributos de Auditoria
       Fec_creacion     DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT ON TABLE EVENTO IS 'TABLA DE EVENTO';

