--TABLA: ACTIVIDAD POR PERSONA


/*
Fecha: 25/09/2015
Autor: Samantha Arburola
DescripciOn: Tabla para almacenar las actividades de una persona
*/

CREATE TABLE ACTIVIDAD_x_PERSONA
(     
       ACTIVIDAD_RECREATIVA_ID NUMBER(6),
       CONSTRAINT FK_ACTIVIDAD_RECREATIVA_ID FOREIGN KEY(ACTIVIDAD_RECREATIVA_ID) REFERENCES ACTIVIDAD_RECREATIVA(ACTIVIDAD_RECREATIVA_ID),
       
       PERSONA_ID NUMBER(6),
       CONSTRAINT FK_PERSONA_AxP FOREIGN KEY (PERSONA_ID) REFERENCES PERSONA(PERSONA_ID),
       
       CONSTRAINT PK_ACT_RECREA_X_PERSONA PRIMARY KEY (ACTIVIDAD_RECREATIVA_ID, PERSONA_ID),
       
       FRECUENCIA_ID NUMBER(6),
       CONSTRAINT FK_FRECUENCIA_AxP FOREIGN KEY (FRECUENCIA_ID) REFERENCES FRECUENCIA(FRECUENCIA_ID),
       
       -- Atributos de Auditoria
       Fec_creacion 	  DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT ON TABLE ACTIVIDAD_x_PERSONA IS 'TABLA DE LAS ACTIVIDADES RECREATIVAS DE UNA PERSONA';
