create or replace package estadisticas is
       function count_personas return number;
       function count_mujeres return number;
       function count_hombres return number;
       procedure count_edad(resultado out sys_refcursor);
       procedure count_nacionalidad(resultado out sys_refcursor);
       procedure count_pais(resultado out sys_refcursor);
       procedure count_ciudad(resultado out sys_refcursor);
       procedure count_religion(resultado out sys_refcursor);
       procedure count_zodiaco(resultado out sys_refcursor);
       procedure count_est_civil(resultado out sys_refcursor);
       function count_can_hijos return number;
       function count_quiere_hijos return number;
       procedure count_altura(resultado out sys_refcursor);
       procedure count_peso(resultado out sys_refcursor);
       procedure count_contextura(resultado out sys_refcursor);
       procedure count_piel(resultado out sys_refcursor);
       procedure count_ojos(resultado out sys_refcursor);
       procedure count_cabello(resultado out sys_refcursor);
       procedure count_escolaridad(resultado out sys_refcursor);
       procedure count_ocupacion(resultado out sys_refcursor);
       procedure count_salario(resultado out sys_refcursor);
       function count_afin_masc return number;
       function count_disp_masc return number;
       procedure count_idiomas(resultado out sys_refcursor);       
       procedure count_deportes(resultado out sys_refcursor);
       procedure count_recreativas(resultado out sys_refcursor);
       procedure count_hobbies(resultado out sys_refcursor);
       procedure count_vicios(resultado out sys_refcursor);
      
end estadisticas;
