CREATE OR REPLACE PACKAGE INSERTS_CATALOGO IS

       PROCEDURE INSERTAR_CATALOGO_CIUDAD(pCiudad IN VARCHAR2, idPais IN NUMBER);

       PROCEDURE INSERTAR_CATALOGO_EDAD(pRango IN VARCHAR2);

       PROCEDURE INSERTAR_CATALOGO_VICIO(pNombre IN VARCHAR2);

       PROCEDURE INSERTAR_CATALOGO_ZODIACO(pSigno IN VARCHAR2, fechaInicio IN DATE, fechaFinal IN DATE);

       PROCEDURE INSERTAR_CATALOGO_SALARIO(pRango IN VARCHAR2);

       PROCEDURE INSERTAR_CATALOGO_RELIGION(pNombre IN VARCHAR2);

       PROCEDURE INSERTAR_CATALOGO_PESO(pRango IN VARCHAR2);

END INSERTS_CATALOGO;
/
