CREATE OR REPLACE PACKAGE UPDATES_CATALOGOS IS

       PROCEDURE UPDATE_CATALOGO_CIUDAD(pCiudad IN VARCHAR2, idPais IN NUMBER);

       PROCEDURE UPDATE_CATALOGO_EDAD(pRango IN VARCHAR2);

       PROCEDURE UPDATE_CATALOGO_VICIO(pNombre IN VARCHAR2);

       PROCEDURE UPDATE_CATALOGO_SIGNO_ZODIACAL(pSigno IN VARCHAR2, fechaInicio IN DATE, fechaFinal IN DATE);

       PROCEDURE UPDATE_CATALOGO_SALARIO(pRango IN VARCHAR2);

       PROCEDURE UPDATE_CATALOGO_RELIGION(pNombre IN VARCHAR2);

       PROCEDURE UPDATE_CATALOGO_PESO(pRango IN VARCHAR2);

END UPDATES_CATALOGOS;
