CREATE OR REPLACE PACKAGE INSERTS_CATALOGO IS

       PROCEDURE INSERTAR_CATALOGO_CIUDAD(pCiudad, idPais);
       
       PROCEDURE INSERTAR_CATALOGO_EDAD(pRango);
         
       PROCEDURE INSERTAR_CATALOGO_VICIO(pNombre);
       
       PROCEDURE INSERTAR_CATALOGO_SIGNO_ZODIACAL(pSigno, fechaInicio, fechaFinal);
       
       PROCEDURE INSERTAR_CATALOGO_SALARIO(pRango);
       
       PROCEDURE INSERTAR_CATALOGO_RELIGION(pNombre);
       
       PROCEDURE INSERTAR_CATALOGO_PESO(pRango);

END INSERTS_CATALOGO;       
       
