CREATE OR REPLACE PACKAGE BODY INSERTS IS

       PROCEDURE INSERTAR_CATALOGO_CIUDAD(pCiudad, idPais)
         AS
                 INSERT INTO CIUDAD(CIUDAD_ID, CIUDAD, PAIS_ID)
                 VALUES(S_CIUDAD_ID.NEXTVAL, pCuidad, idPais);
         END INSERTAR_CATALOGO_CIUDAD;
       
       PROCEDURE INSERTAR_CATALOGO_EDAD(pRango)
         AS
                 INSERT INTO EDAD(EDAD_ID,RANGO)
                 VALUES(S_EDAD_ID.NEXTVAL, pRango)
         END INSERTAR_CATALOGO_EDAD;
         
       PROCEDURE INSERTAR_CATALOGO_VICIO(pNombre)
       
       PROCEDURE INSERTAR_CATALOGO_SIGNO_ZODIACAL(pSigno, fechaInicio, fechaFinal)
       
       PROCEDURE INSERTAR_CATALOGO_SALARIO(pRango)
       
       PROCEDURE INSERTAR_CATALOGO_RELIGION(pNombre)
       
       PROCEDURE INSERTAR_CATALOGO_PESO(pRango)

END INSERTS; 
