--CATALOGO: CONTEXTURA
CREATE TABLE CONTEXTURA
(
  CONTEXTURA_ID NUMBER(6),
  CONSTRAINT PK_CONTEXTURA PRIMARY KEY(CONTEXTURA_ID),
  TIPO VARCHAR2(30) CONSTRAINT CONTEXTURA_TIPO_NN NOT NULL
);

COMMENT ON TABLE CONTEXTURA IS 'CATALOGO DE CONTEXTURA';