-- CATALOGO: COLOR DE CABELLO
CREATE TABLE CCABELLO
(
  CCABELLO_ID NUMBER(6),
  CONSTRAINT PK_CCABELLO PRIMARY KEY(CCABELLO_ID),
  NOMBRE VARCHAR2(15) CONSTRAINT CCABELLO_NOMBRE_NN NOT NULL,
  -- Atributos de Auditoria
       Fec_creacion 	  DATE,
       Usuario_creacion   VARCHAR2(10),
       Fec_ultima_modificacion     DATE,
       Usuario_ultima_modificacion VARCHAR2(10)
);

COMMENT ON TABLE CCABELLO IS 'CATALOGO PARA COLOR DE CABELLO';
